# coding: utf-8

"""
    PubMan REST API

    This is an automatically generated REST API client for PubMan.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from mpg_pure.api_client import ApiClient


class OrganizationsApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def child_organizations_using_get(self, ou_id, **kwargs):  # noqa: E501
        """childOrganizations  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.child_organizations_using_get(ou_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str ou_id: ouId (required)
        :return: list[AffiliationDbVO]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.child_organizations_using_get_with_http_info(ou_id, **kwargs)  # noqa: E501
        else:
            (data) = self.child_organizations_using_get_with_http_info(ou_id, **kwargs)  # noqa: E501
            return data

    def child_organizations_using_get_with_http_info(self, ou_id, **kwargs):  # noqa: E501
        """childOrganizations  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.child_organizations_using_get_with_http_info(ou_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str ou_id: ouId (required)
        :return: list[AffiliationDbVO]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['ou_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method child_organizations_using_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'ou_id' is set
        if ('ou_id' not in params or
                params['ou_id'] is None):
            raise ValueError("Missing the required parameter `ou_id` when calling `child_organizations_using_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'ou_id' in params:
            path_params['ouId'] = params['ou_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/ous/{ouId}/children', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[AffiliationDbVO]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def close_using_put1(self, authorization, modification_date, ou_id, **kwargs):  # noqa: E501
        """close  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.close_using_put1(authorization, modification_date, ou_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str authorization: Authorization (required)
        :param str modification_date: modificationDate (required)
        :param str ou_id: ouId (required)
        :return: AffiliationDbVO
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.close_using_put1_with_http_info(authorization, modification_date, ou_id, **kwargs)  # noqa: E501
        else:
            (data) = self.close_using_put1_with_http_info(authorization, modification_date, ou_id, **kwargs)  # noqa: E501
            return data

    def close_using_put1_with_http_info(self, authorization, modification_date, ou_id, **kwargs):  # noqa: E501
        """close  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.close_using_put1_with_http_info(authorization, modification_date, ou_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str authorization: Authorization (required)
        :param str modification_date: modificationDate (required)
        :param str ou_id: ouId (required)
        :return: AffiliationDbVO
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['authorization', 'modification_date', 'ou_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method close_using_put1" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'authorization' is set
        if ('authorization' not in params or
                params['authorization'] is None):
            raise ValueError("Missing the required parameter `authorization` when calling `close_using_put1`")  # noqa: E501
        # verify the required parameter 'modification_date' is set
        if ('modification_date' not in params or
                params['modification_date'] is None):
            raise ValueError("Missing the required parameter `modification_date` when calling `close_using_put1`")  # noqa: E501
        # verify the required parameter 'ou_id' is set
        if ('ou_id' not in params or
                params['ou_id'] is None):
            raise ValueError("Missing the required parameter `ou_id` when calling `close_using_put1`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'ou_id' in params:
            path_params['ouId'] = params['ou_id']  # noqa: E501

        query_params = []

        header_params = {}
        if 'authorization' in params:
            header_params['Authorization'] = params['authorization']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if 'modification_date' in params:
            body_params = params['modification_date']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/ous/{ouId}/close', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AffiliationDbVO',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def create_using_post2(self, authorization, ou, **kwargs):  # noqa: E501
        """create  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_using_post2(authorization, ou, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str authorization: Authorization (required)
        :param AffiliationDbVO ou: ou (required)
        :return: AffiliationDbVO
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_using_post2_with_http_info(authorization, ou, **kwargs)  # noqa: E501
        else:
            (data) = self.create_using_post2_with_http_info(authorization, ou, **kwargs)  # noqa: E501
            return data

    def create_using_post2_with_http_info(self, authorization, ou, **kwargs):  # noqa: E501
        """create  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_using_post2_with_http_info(authorization, ou, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str authorization: Authorization (required)
        :param AffiliationDbVO ou: ou (required)
        :return: AffiliationDbVO
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['authorization', 'ou']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_using_post2" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'authorization' is set
        if ('authorization' not in params or
                params['authorization'] is None):
            raise ValueError("Missing the required parameter `authorization` when calling `create_using_post2`")  # noqa: E501
        # verify the required parameter 'ou' is set
        if ('ou' not in params or
                params['ou'] is None):
            raise ValueError("Missing the required parameter `ou` when calling `create_using_post2`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}
        if 'authorization' in params:
            header_params['Authorization'] = params['authorization']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if 'ou' in params:
            body_params = params['ou']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/ous', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AffiliationDbVO',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_using_delete2(self, authorization, ou_id, **kwargs):  # noqa: E501
        """delete  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_using_delete2(authorization, ou_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str authorization: Authorization (required)
        :param str ou_id: ouId (required)
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_using_delete2_with_http_info(authorization, ou_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_using_delete2_with_http_info(authorization, ou_id, **kwargs)  # noqa: E501
            return data

    def delete_using_delete2_with_http_info(self, authorization, ou_id, **kwargs):  # noqa: E501
        """delete  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_using_delete2_with_http_info(authorization, ou_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str authorization: Authorization (required)
        :param str ou_id: ouId (required)
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['authorization', 'ou_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_using_delete2" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'authorization' is set
        if ('authorization' not in params or
                params['authorization'] is None):
            raise ValueError("Missing the required parameter `authorization` when calling `delete_using_delete2`")  # noqa: E501
        # verify the required parameter 'ou_id' is set
        if ('ou_id' not in params or
                params['ou_id'] is None):
            raise ValueError("Missing the required parameter `ou_id` when calling `delete_using_delete2`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'ou_id' in params:
            path_params['ouId'] = params['ou_id']  # noqa: E501

        query_params = []

        header_params = {}
        if 'authorization' in params:
            header_params['Authorization'] = params['authorization']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/ous/{ouId}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='object',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_all_using_get1(self, **kwargs):  # noqa: E501
        """getAll  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all_using_get1(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str authorization: Authorization
        :param int _from: from
        :param int size: size
        :return: SearchRetrieveResponseVOAffiliationDbVO
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_all_using_get1_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_all_using_get1_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_all_using_get1_with_http_info(self, **kwargs):  # noqa: E501
        """getAll  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all_using_get1_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str authorization: Authorization
        :param int _from: from
        :param int size: size
        :return: SearchRetrieveResponseVOAffiliationDbVO
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['authorization', '_from', 'size']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_all_using_get1" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if '_from' in params:
            query_params.append(('from', params['_from']))  # noqa: E501
        if 'size' in params:
            query_params.append(('size', params['size']))  # noqa: E501

        header_params = {}
        if 'authorization' in params:
            header_params['Authorization'] = params['authorization']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/ous', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SearchRetrieveResponseVOAffiliationDbVO',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_using_get2(self, ou_id, **kwargs):  # noqa: E501
        """get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_using_get2(ou_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str ou_id: ouId (required)
        :param str authorization: Authorization
        :return: AffiliationDbVO
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_using_get2_with_http_info(ou_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_using_get2_with_http_info(ou_id, **kwargs)  # noqa: E501
            return data

    def get_using_get2_with_http_info(self, ou_id, **kwargs):  # noqa: E501
        """get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_using_get2_with_http_info(ou_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str ou_id: ouId (required)
        :param str authorization: Authorization
        :return: AffiliationDbVO
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['ou_id', 'authorization']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_using_get2" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'ou_id' is set
        if ('ou_id' not in params or
                params['ou_id'] is None):
            raise ValueError("Missing the required parameter `ou_id` when calling `get_using_get2`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'ou_id' in params:
            path_params['ouId'] = params['ou_id']  # noqa: E501

        query_params = []

        header_params = {}
        if 'authorization' in params:
            header_params['Authorization'] = params['authorization']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/ous/{ouId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AffiliationDbVO',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def open_using_put1(self, authorization, modification_date, ou_id, **kwargs):  # noqa: E501
        """open  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.open_using_put1(authorization, modification_date, ou_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str authorization: Authorization (required)
        :param str modification_date: modificationDate (required)
        :param str ou_id: ouId (required)
        :return: AffiliationDbVO
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.open_using_put1_with_http_info(authorization, modification_date, ou_id, **kwargs)  # noqa: E501
        else:
            (data) = self.open_using_put1_with_http_info(authorization, modification_date, ou_id, **kwargs)  # noqa: E501
            return data

    def open_using_put1_with_http_info(self, authorization, modification_date, ou_id, **kwargs):  # noqa: E501
        """open  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.open_using_put1_with_http_info(authorization, modification_date, ou_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str authorization: Authorization (required)
        :param str modification_date: modificationDate (required)
        :param str ou_id: ouId (required)
        :return: AffiliationDbVO
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['authorization', 'modification_date', 'ou_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method open_using_put1" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'authorization' is set
        if ('authorization' not in params or
                params['authorization'] is None):
            raise ValueError("Missing the required parameter `authorization` when calling `open_using_put1`")  # noqa: E501
        # verify the required parameter 'modification_date' is set
        if ('modification_date' not in params or
                params['modification_date'] is None):
            raise ValueError("Missing the required parameter `modification_date` when calling `open_using_put1`")  # noqa: E501
        # verify the required parameter 'ou_id' is set
        if ('ou_id' not in params or
                params['ou_id'] is None):
            raise ValueError("Missing the required parameter `ou_id` when calling `open_using_put1`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'ou_id' in params:
            path_params['ouId'] = params['ou_id']  # noqa: E501

        query_params = []

        header_params = {}
        if 'authorization' in params:
            header_params['Authorization'] = params['authorization']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if 'modification_date' in params:
            body_params = params['modification_date']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/ous/{ouId}/open', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AffiliationDbVO',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def query_using_post(self, query, **kwargs):  # noqa: E501
        """query  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.query_using_post(query, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param JsonNode query: query (required)
        :param str authorization: Authorization
        :return: SearchRetrieveResponseVOAffiliationDbVO
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.query_using_post_with_http_info(query, **kwargs)  # noqa: E501
        else:
            (data) = self.query_using_post_with_http_info(query, **kwargs)  # noqa: E501
            return data

    def query_using_post_with_http_info(self, query, **kwargs):  # noqa: E501
        """query  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.query_using_post_with_http_info(query, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param JsonNode query: query (required)
        :param str authorization: Authorization
        :return: SearchRetrieveResponseVOAffiliationDbVO
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['query', 'authorization']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method query_using_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'query' is set
        if ('query' not in params or
                params['query'] is None):
            raise ValueError("Missing the required parameter `query` when calling `query_using_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}
        if 'authorization' in params:
            header_params['Authorization'] = params['authorization']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if 'query' in params:
            body_params = params['query']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/ous/search', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SearchRetrieveResponseVOAffiliationDbVO',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def top_level_using_get(self, **kwargs):  # noqa: E501
        """topLevel  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.top_level_using_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[AffiliationDbVO]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.top_level_using_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.top_level_using_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def top_level_using_get_with_http_info(self, **kwargs):  # noqa: E501
        """topLevel  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.top_level_using_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[AffiliationDbVO]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method top_level_using_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/ous/toplevel', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[AffiliationDbVO]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_using_put2(self, authorization, ou, ou_id, **kwargs):  # noqa: E501
        """update  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_using_put2(authorization, ou, ou_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str authorization: Authorization (required)
        :param AffiliationDbVO ou: ou (required)
        :param str ou_id: ouId (required)
        :return: AffiliationDbVO
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_using_put2_with_http_info(authorization, ou, ou_id, **kwargs)  # noqa: E501
        else:
            (data) = self.update_using_put2_with_http_info(authorization, ou, ou_id, **kwargs)  # noqa: E501
            return data

    def update_using_put2_with_http_info(self, authorization, ou, ou_id, **kwargs):  # noqa: E501
        """update  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_using_put2_with_http_info(authorization, ou, ou_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str authorization: Authorization (required)
        :param AffiliationDbVO ou: ou (required)
        :param str ou_id: ouId (required)
        :return: AffiliationDbVO
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['authorization', 'ou', 'ou_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_using_put2" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'authorization' is set
        if ('authorization' not in params or
                params['authorization'] is None):
            raise ValueError("Missing the required parameter `authorization` when calling `update_using_put2`")  # noqa: E501
        # verify the required parameter 'ou' is set
        if ('ou' not in params or
                params['ou'] is None):
            raise ValueError("Missing the required parameter `ou` when calling `update_using_put2`")  # noqa: E501
        # verify the required parameter 'ou_id' is set
        if ('ou_id' not in params or
                params['ou_id'] is None):
            raise ValueError("Missing the required parameter `ou_id` when calling `update_using_put2`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'ou_id' in params:
            path_params['ouId'] = params['ou_id']  # noqa: E501

        query_params = []

        header_params = {}
        if 'authorization' in params:
            header_params['Authorization'] = params['authorization']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if 'ou' in params:
            body_params = params['ou']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/ous/{ouId}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AffiliationDbVO',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
