# coding: utf-8

"""
    PubMan REST API

    This is an automatically generated REST API client for PubMan.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class AffiliationDbRO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'creation_date': 'datetime',
        'creator': 'AccountUserDbRO',
        'last_modification_date': 'datetime',
        'modifier': 'AccountUserDbRO',
        'name': 'str',
        'object_id': 'str'
    }

    attribute_map = {
        'creation_date': 'creationDate',
        'creator': 'creator',
        'last_modification_date': 'lastModificationDate',
        'modifier': 'modifier',
        'name': 'name',
        'object_id': 'objectId'
    }

    def __init__(self, creation_date=None, creator=None, last_modification_date=None, modifier=None, name=None, object_id=None):  # noqa: E501
        """AffiliationDbRO - a model defined in Swagger"""  # noqa: E501

        self._creation_date = None
        self._creator = None
        self._last_modification_date = None
        self._modifier = None
        self._name = None
        self._object_id = None
        self.discriminator = None

        if creation_date is not None:
            self.creation_date = creation_date
        if creator is not None:
            self.creator = creator
        if last_modification_date is not None:
            self.last_modification_date = last_modification_date
        if modifier is not None:
            self.modifier = modifier
        if name is not None:
            self.name = name
        if object_id is not None:
            self.object_id = object_id

    @property
    def creation_date(self):
        """Gets the creation_date of this AffiliationDbRO.  # noqa: E501


        :return: The creation_date of this AffiliationDbRO.  # noqa: E501
        :rtype: datetime
        """
        return self._creation_date

    @creation_date.setter
    def creation_date(self, creation_date):
        """Sets the creation_date of this AffiliationDbRO.


        :param creation_date: The creation_date of this AffiliationDbRO.  # noqa: E501
        :type: datetime
        """

        self._creation_date = creation_date

    @property
    def creator(self):
        """Gets the creator of this AffiliationDbRO.  # noqa: E501


        :return: The creator of this AffiliationDbRO.  # noqa: E501
        :rtype: AccountUserDbRO
        """
        return self._creator

    @creator.setter
    def creator(self, creator):
        """Sets the creator of this AffiliationDbRO.


        :param creator: The creator of this AffiliationDbRO.  # noqa: E501
        :type: AccountUserDbRO
        """

        self._creator = creator

    @property
    def last_modification_date(self):
        """Gets the last_modification_date of this AffiliationDbRO.  # noqa: E501


        :return: The last_modification_date of this AffiliationDbRO.  # noqa: E501
        :rtype: datetime
        """
        return self._last_modification_date

    @last_modification_date.setter
    def last_modification_date(self, last_modification_date):
        """Sets the last_modification_date of this AffiliationDbRO.


        :param last_modification_date: The last_modification_date of this AffiliationDbRO.  # noqa: E501
        :type: datetime
        """

        self._last_modification_date = last_modification_date

    @property
    def modifier(self):
        """Gets the modifier of this AffiliationDbRO.  # noqa: E501


        :return: The modifier of this AffiliationDbRO.  # noqa: E501
        :rtype: AccountUserDbRO
        """
        return self._modifier

    @modifier.setter
    def modifier(self, modifier):
        """Sets the modifier of this AffiliationDbRO.


        :param modifier: The modifier of this AffiliationDbRO.  # noqa: E501
        :type: AccountUserDbRO
        """

        self._modifier = modifier

    @property
    def name(self):
        """Gets the name of this AffiliationDbRO.  # noqa: E501


        :return: The name of this AffiliationDbRO.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AffiliationDbRO.


        :param name: The name of this AffiliationDbRO.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def object_id(self):
        """Gets the object_id of this AffiliationDbRO.  # noqa: E501


        :return: The object_id of this AffiliationDbRO.  # noqa: E501
        :rtype: str
        """
        return self._object_id

    @object_id.setter
    def object_id(self, object_id):
        """Sets the object_id of this AffiliationDbRO.


        :param object_id: The object_id of this AffiliationDbRO.  # noqa: E501
        :type: str
        """

        self._object_id = object_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AffiliationDbRO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AffiliationDbRO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
