# coding: utf-8

"""
    PubMan REST API

    This is an automatically generated REST API client for PubMan.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class EventVO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'alternative_titles': 'list[AlternativeTitleVO]',
        'end_date': 'str',
        'invitation_status': 'str',
        'place': 'str',
        'start_date': 'str',
        'title': 'str'
    }

    attribute_map = {
        'alternative_titles': 'alternativeTitles',
        'end_date': 'endDate',
        'invitation_status': 'invitationStatus',
        'place': 'place',
        'start_date': 'startDate',
        'title': 'title'
    }

    def __init__(self, alternative_titles=None, end_date=None, invitation_status=None, place=None, start_date=None, title=None):  # noqa: E501
        """EventVO - a model defined in Swagger"""  # noqa: E501

        self._alternative_titles = None
        self._end_date = None
        self._invitation_status = None
        self._place = None
        self._start_date = None
        self._title = None
        self.discriminator = None

        if alternative_titles is not None:
            self.alternative_titles = alternative_titles
        if end_date is not None:
            self.end_date = end_date
        if invitation_status is not None:
            self.invitation_status = invitation_status
        if place is not None:
            self.place = place
        if start_date is not None:
            self.start_date = start_date
        if title is not None:
            self.title = title

    @property
    def alternative_titles(self):
        """Gets the alternative_titles of this EventVO.  # noqa: E501


        :return: The alternative_titles of this EventVO.  # noqa: E501
        :rtype: list[AlternativeTitleVO]
        """
        return self._alternative_titles

    @alternative_titles.setter
    def alternative_titles(self, alternative_titles):
        """Sets the alternative_titles of this EventVO.


        :param alternative_titles: The alternative_titles of this EventVO.  # noqa: E501
        :type: list[AlternativeTitleVO]
        """

        self._alternative_titles = alternative_titles

    @property
    def end_date(self):
        """Gets the end_date of this EventVO.  # noqa: E501


        :return: The end_date of this EventVO.  # noqa: E501
        :rtype: str
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this EventVO.


        :param end_date: The end_date of this EventVO.  # noqa: E501
        :type: str
        """

        self._end_date = end_date

    @property
    def invitation_status(self):
        """Gets the invitation_status of this EventVO.  # noqa: E501


        :return: The invitation_status of this EventVO.  # noqa: E501
        :rtype: str
        """
        return self._invitation_status

    @invitation_status.setter
    def invitation_status(self, invitation_status):
        """Sets the invitation_status of this EventVO.


        :param invitation_status: The invitation_status of this EventVO.  # noqa: E501
        :type: str
        """
        allowed_values = ["INVITED"]  # noqa: E501
        if invitation_status not in allowed_values:
            raise ValueError(
                "Invalid value for `invitation_status` ({0}), must be one of {1}"  # noqa: E501
                .format(invitation_status, allowed_values)
            )

        self._invitation_status = invitation_status

    @property
    def place(self):
        """Gets the place of this EventVO.  # noqa: E501


        :return: The place of this EventVO.  # noqa: E501
        :rtype: str
        """
        return self._place

    @place.setter
    def place(self, place):
        """Sets the place of this EventVO.


        :param place: The place of this EventVO.  # noqa: E501
        :type: str
        """

        self._place = place

    @property
    def start_date(self):
        """Gets the start_date of this EventVO.  # noqa: E501


        :return: The start_date of this EventVO.  # noqa: E501
        :rtype: str
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this EventVO.


        :param start_date: The start_date of this EventVO.  # noqa: E501
        :type: str
        """

        self._start_date = start_date

    @property
    def title(self):
        """Gets the title of this EventVO.  # noqa: E501


        :return: The title of this EventVO.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this EventVO.


        :param title: The title of this EventVO.  # noqa: E501
        :type: str
        """

        self._title = title

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EventVO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EventVO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
