# coding: utf-8

"""
    PubMan REST API

    This is an automatically generated REST API client for PubMan.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class FundingProgramVO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'identifiers': 'list[IdentifierVO]',
        'title': 'str'
    }

    attribute_map = {
        'identifiers': 'identifiers',
        'title': 'title'
    }

    def __init__(self, identifiers=None, title=None):  # noqa: E501
        """FundingProgramVO - a model defined in Swagger"""  # noqa: E501

        self._identifiers = None
        self._title = None
        self.discriminator = None

        if identifiers is not None:
            self.identifiers = identifiers
        if title is not None:
            self.title = title

    @property
    def identifiers(self):
        """Gets the identifiers of this FundingProgramVO.  # noqa: E501


        :return: The identifiers of this FundingProgramVO.  # noqa: E501
        :rtype: list[IdentifierVO]
        """
        return self._identifiers

    @identifiers.setter
    def identifiers(self, identifiers):
        """Sets the identifiers of this FundingProgramVO.


        :param identifiers: The identifiers of this FundingProgramVO.  # noqa: E501
        :type: list[IdentifierVO]
        """

        self._identifiers = identifiers

    @property
    def title(self):
        """Gets the title of this FundingProgramVO.  # noqa: E501


        :return: The title of this FundingProgramVO.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this FundingProgramVO.


        :param title: The title of this FundingProgramVO.  # noqa: E501
        :type: str
        """

        self._title = title

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FundingProgramVO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FundingProgramVO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
