# coding: utf-8

"""
    PubMan REST API

    This is an automatically generated REST API client for PubMan.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ItemVersionRO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'modification_date': 'datetime',
        'modifier': 'AccountUserDbRO',
        'object_id': 'str',
        'version_number': 'int',
        'version_pid': 'str',
        'version_state': 'str'
    }

    attribute_map = {
        'modification_date': 'modificationDate',
        'modifier': 'modifier',
        'object_id': 'objectId',
        'version_number': 'versionNumber',
        'version_pid': 'versionPid',
        'version_state': 'versionState'
    }

    def __init__(self, modification_date=None, modifier=None, object_id=None, version_number=None, version_pid=None, version_state=None):  # noqa: E501
        """ItemVersionRO - a model defined in Swagger"""  # noqa: E501

        self._modification_date = None
        self._modifier = None
        self._object_id = None
        self._version_number = None
        self._version_pid = None
        self._version_state = None
        self.discriminator = None

        if modification_date is not None:
            self.modification_date = modification_date
        if modifier is not None:
            self.modifier = modifier
        if object_id is not None:
            self.object_id = object_id
        if version_number is not None:
            self.version_number = version_number
        if version_pid is not None:
            self.version_pid = version_pid
        if version_state is not None:
            self.version_state = version_state

    @property
    def modification_date(self):
        """Gets the modification_date of this ItemVersionRO.  # noqa: E501


        :return: The modification_date of this ItemVersionRO.  # noqa: E501
        :rtype: datetime
        """
        return self._modification_date

    @modification_date.setter
    def modification_date(self, modification_date):
        """Sets the modification_date of this ItemVersionRO.


        :param modification_date: The modification_date of this ItemVersionRO.  # noqa: E501
        :type: datetime
        """

        self._modification_date = modification_date

    @property
    def modifier(self):
        """Gets the modifier of this ItemVersionRO.  # noqa: E501


        :return: The modifier of this ItemVersionRO.  # noqa: E501
        :rtype: AccountUserDbRO
        """
        return self._modifier

    @modifier.setter
    def modifier(self, modifier):
        """Sets the modifier of this ItemVersionRO.


        :param modifier: The modifier of this ItemVersionRO.  # noqa: E501
        :type: AccountUserDbRO
        """

        self._modifier = modifier

    @property
    def object_id(self):
        """Gets the object_id of this ItemVersionRO.  # noqa: E501


        :return: The object_id of this ItemVersionRO.  # noqa: E501
        :rtype: str
        """
        return self._object_id

    @object_id.setter
    def object_id(self, object_id):
        """Sets the object_id of this ItemVersionRO.


        :param object_id: The object_id of this ItemVersionRO.  # noqa: E501
        :type: str
        """

        self._object_id = object_id

    @property
    def version_number(self):
        """Gets the version_number of this ItemVersionRO.  # noqa: E501


        :return: The version_number of this ItemVersionRO.  # noqa: E501
        :rtype: int
        """
        return self._version_number

    @version_number.setter
    def version_number(self, version_number):
        """Sets the version_number of this ItemVersionRO.


        :param version_number: The version_number of this ItemVersionRO.  # noqa: E501
        :type: int
        """

        self._version_number = version_number

    @property
    def version_pid(self):
        """Gets the version_pid of this ItemVersionRO.  # noqa: E501


        :return: The version_pid of this ItemVersionRO.  # noqa: E501
        :rtype: str
        """
        return self._version_pid

    @version_pid.setter
    def version_pid(self, version_pid):
        """Sets the version_pid of this ItemVersionRO.


        :param version_pid: The version_pid of this ItemVersionRO.  # noqa: E501
        :type: str
        """

        self._version_pid = version_pid

    @property
    def version_state(self):
        """Gets the version_state of this ItemVersionRO.  # noqa: E501


        :return: The version_state of this ItemVersionRO.  # noqa: E501
        :rtype: str
        """
        return self._version_state

    @version_state.setter
    def version_state(self, version_state):
        """Sets the version_state of this ItemVersionRO.


        :param version_state: The version_state of this ItemVersionRO.  # noqa: E501
        :type: str
        """
        allowed_values = ["PENDING", "SUBMITTED", "RELEASED", "WITHDRAWN", "IN_REVISION"]  # noqa: E501
        if version_state not in allowed_values:
            raise ValueError(
                "Invalid value for `version_state` ({0}), must be one of {1}"  # noqa: E501
                .format(version_state, allowed_values)
            )

        self._version_state = version_state

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ItemVersionRO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ItemVersionRO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
