# coding: utf-8

"""
    PubMan REST API

    This is an automatically generated REST API client for PubMan.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class OrganizationVO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'address': 'str',
        'identifier': 'str',
        'identifier_path': 'list[str]',
        'name': 'str'
    }

    attribute_map = {
        'address': 'address',
        'identifier': 'identifier',
        'identifier_path': 'identifierPath',
        'name': 'name'
    }

    def __init__(self, address=None, identifier=None, identifier_path=None, name=None):  # noqa: E501
        """OrganizationVO - a model defined in Swagger"""  # noqa: E501

        self._address = None
        self._identifier = None
        self._identifier_path = None
        self._name = None
        self.discriminator = None

        if address is not None:
            self.address = address
        if identifier is not None:
            self.identifier = identifier
        if identifier_path is not None:
            self.identifier_path = identifier_path
        if name is not None:
            self.name = name

    @property
    def address(self):
        """Gets the address of this OrganizationVO.  # noqa: E501


        :return: The address of this OrganizationVO.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this OrganizationVO.


        :param address: The address of this OrganizationVO.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def identifier(self):
        """Gets the identifier of this OrganizationVO.  # noqa: E501


        :return: The identifier of this OrganizationVO.  # noqa: E501
        :rtype: str
        """
        return self._identifier

    @identifier.setter
    def identifier(self, identifier):
        """Sets the identifier of this OrganizationVO.


        :param identifier: The identifier of this OrganizationVO.  # noqa: E501
        :type: str
        """

        self._identifier = identifier

    @property
    def identifier_path(self):
        """Gets the identifier_path of this OrganizationVO.  # noqa: E501


        :return: The identifier_path of this OrganizationVO.  # noqa: E501
        :rtype: list[str]
        """
        return self._identifier_path

    @identifier_path.setter
    def identifier_path(self, identifier_path):
        """Sets the identifier_path of this OrganizationVO.


        :param identifier_path: The identifier_path of this OrganizationVO.  # noqa: E501
        :type: list[str]
        """

        self._identifier_path = identifier_path

    @property
    def name(self):
        """Gets the name of this OrganizationVO.  # noqa: E501


        :return: The name of this OrganizationVO.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this OrganizationVO.


        :param name: The name of this OrganizationVO.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrganizationVO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrganizationVO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
