# coding: utf-8

"""
    PubMan REST API

    This is an automatically generated REST API client for PubMan.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class TaskParamVO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'comment': 'str',
        'last_modification_date': 'datetime',
        'password': 'str'
    }

    attribute_map = {
        'comment': 'comment',
        'last_modification_date': 'lastModificationDate',
        'password': 'password'
    }

    def __init__(self, comment=None, last_modification_date=None, password=None):  # noqa: E501
        """TaskParamVO - a model defined in Swagger"""  # noqa: E501

        self._comment = None
        self._last_modification_date = None
        self._password = None
        self.discriminator = None

        if comment is not None:
            self.comment = comment
        if last_modification_date is not None:
            self.last_modification_date = last_modification_date
        if password is not None:
            self.password = password

    @property
    def comment(self):
        """Gets the comment of this TaskParamVO.  # noqa: E501


        :return: The comment of this TaskParamVO.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this TaskParamVO.


        :param comment: The comment of this TaskParamVO.  # noqa: E501
        :type: str
        """

        self._comment = comment

    @property
    def last_modification_date(self):
        """Gets the last_modification_date of this TaskParamVO.  # noqa: E501


        :return: The last_modification_date of this TaskParamVO.  # noqa: E501
        :rtype: datetime
        """
        return self._last_modification_date

    @last_modification_date.setter
    def last_modification_date(self, last_modification_date):
        """Sets the last_modification_date of this TaskParamVO.


        :param last_modification_date: The last_modification_date of this TaskParamVO.  # noqa: E501
        :type: datetime
        """

        self._last_modification_date = last_modification_date

    @property
    def password(self):
        """Gets the password of this TaskParamVO.  # noqa: E501


        :return: The password of this TaskParamVO.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this TaskParamVO.


        :param password: The password of this TaskParamVO.  # noqa: E501
        :type: str
        """

        self._password = password

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TaskParamVO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TaskParamVO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
